version: '3'
services:
  jekyll:
    image: starefossen/github-pages
    container_name: "harry-personal-blog"
    environment:
      - "JEKYLL_GITHUB_TOKEN:236ad3de4c62df8a1d09a79a3666e0dc4da0d55c"
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
    tty: true